# Generated by Django 4.1 on 2022-08-26 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=30)),
                ('country_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=30)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=16, unique=True)),
                ('business_type', models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate'), ('Proprietor', 'Proprietor')], max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('country_code', models.CharField(max_length=3)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.state')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.state'),
        ),
    ]
